name:                i18n-resource
version:             0.1.0.0
github:              "natsuki14/i18n-resource"
license:             PublicDomain
author:              "Natsuki Kawai"
maintainer:          "kawai@charon.tech"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/natsuki14/i18n-resource#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- case-insensitive
- containers
- http-media

ghc-options:
- -Wno-tabs

library:
  source-dirs: src

tests:
  i18n-resource-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - i18n-resource
    - HUnit-unicode
